services:
  sqlserver:
    container_name: doctorapp-data
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DA@123123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql 

  clean-architecture:
    container_name: doctorapp
    image: doctorapp:latest
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver

volumes:
  mssqldata:  
